function [Hd, f_info] = cheby2_2_8_bandpass
%IIR_2_8_BANDPASS Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.9 and Signal Processing Toolbox 8.5.
% Generated on: 16-Mar-2021 11:39:53

% Chebyshev Type II Bandpass filter designed using FDESIGN.BANDPASS.

% All frequency values are in Hz.
f_info.Fs = 1000;  % Sampling Frequency

f_info.Fstop1 = 1.5;         % First Stopband Frequency
f_info.Fpass1 = 2;           % First Passband Frequency
f_info.Fpass2 = 8;           % Second Passband Frequency
f_info.Fstop2 = 9;           % Second Stopband Frequency
f_info.Astop1 = 60;          % First Stopband Attenuation (dB)
f_info.Apass  = 1;           % Passband Ripple (dB)
f_info.Astop2 = 80;          % Second Stopband Attenuation (dB)
f_info.match  = 'passband';  % Band to match exactly
f_info.type   = 'cheby2';

% Construct an FDESIGN object and call its CHEBY2 method.
h  = fdesign.bandpass(f_info.Fstop1, f_info.Fpass1, f_info.Fpass2,...
                      f_info.Fstop2, f_info.Astop1, f_info.Apass,...
                      f_info.Astop2, f_info.Fs);
Hd = design(h, 'cheby2', 'MatchExactly', f_info.match);

f_info.order = filtord(Hd.sosMatrix);
f_info.stable = isstable(Hd);
% [EOF]



