function [Hd, f_info] = cheby2_49_51_bandstop
%IIR_49-51_BANDSTOP Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.9 and Signal Processing Toolbox 8.5.
% Generated on: 15-Mar-2021 16:10:29

% Chebyshev Type II Bandstop filter designed using FDESIGN.BANDSTOP.

% All frequency values are in Hz.
f_info.Fs = 1000;  % Sampling Frequency

f_info.Fpass1 = 48;          % First Passband Frequency
f_info.Fstop1 = 49;          % First Stopband Frequency
f_info.Fstop2 = 51;          % Second Stopband Frequency
f_info.Fpass2 = 52;          % Second Passband Frequency
f_info.Apass1 = 0.5;         % First Passband Ripple (dB)
f_info.Astop  = 60;          % Stopband Attenuation (dB)
f_info.Apass2 = 1;           % Second Passband Ripple (dB)
f_info.match  = 'passband';  % Band to match exactly
f_info.type   = 'cheby2';

% Construct an FDESIGN object and call its CHEBY2 method.
h  = fdesign.bandstop(f_info.Fpass1, f_info.Fstop1, f_info.Fstop2, f_info.Fpass2, f_info.Apass1, f_info.Astop, ...
                      f_info.Apass2, f_info.Fs);
Hd = design(h, 'cheby2', 'MatchExactly', f_info.match);

f_info.order = filtord(Hd.sosMatrix);
f_info.stable = isstable(Hd);
% [EOF]
