function [Hd, f_info] = cheby2_1_highpass
%CHEBY2_1_HIGHPASS Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.9 and Signal Processing Toolbox 8.5.
% Generated on: 16-Mar-2021 11:37:32

% Chebyshev Type II Highpass filter designed using FDESIGN.HIGHPASS.

% All frequency values are in Hz.
f_info.Fs = 1000;  % Sampling Frequency

f_info.Fstop = 0.1;         % Stopband Frequency
f_info.Fpass = 1;           % Passband Frequency
f_info.Astop = 80;          % Stopband Attenuation (dB)
f_info.Apass = 1;           % Passband Ripple (dB)
f_info.match = 'passband';  % Band to match exactly
f_info.type  = 'cheby2';

% Construct an FDESIGN object and call its CHEBY2 method.
h  = fdesign.highpass(f_info.Fstop, f_info.Fpass, f_info.Astop, f_info.Apass, f_info.Fs);
Hd = design(h, 'cheby2', 'MatchExactly', f_info.match);

f_info.order = filtord(Hd.sosMatrix);
f_info.stable = isstable(Hd);
% [EOF]
