function [Hd, f_info] = cheby2_400_lowpass(Fs)
%CHEBY2_400_LOWPASS Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.9 and Signal Processing Toolbox 8.5.
% Generated on: 07-Jul-2021 12:45:45

% Chebyshev Type II Lowpass filter designed using FDESIGN.LOWPASS.

% All frequency values are in Hz.
%Fs = 24414.125;  % Sampling Frequency

f_info.Fs = Fs;
f_info.Fpass = 400;         % Passband Frequency
f_info.Fstop = 500;         % Stopband Frequency
f_info.Apass = 0.01;           % Passband Ripple (dB)
f_info.Astop = 80;          % Stopband Attenuation (dB)
f_info.match = 'passband';  % Band to match exactly

% Construct an FDESIGN object and call its CHEBY2 method.
h  = fdesign.lowpass(f_info.Fpass, f_info.Fstop, f_info.Apass, f_info.Astop, f_info.Fs);
Hd = design(h, 'cheby2', 'MatchExactly', f_info.match);

f_info.order = filtord(Hd.sosMatrix);
f_info.stable = isstable(Hd);